name: "Run tests"
description: "Run cheerp-utils tests"
inputs:
  flags:
    description: "Flags to pass to run_tests.py"
    required: true
  compiler:
    description: "Compiler to use for tests"
    required: true
    default: "/opt/cheerp/bin/clang++"
  runtime:
    description: "Runtime to use for tests"
    required: true
    default: "node"
runs:
  using: "composite"
  steps:
    - name: Checkout cheerp-utils
      uses: actions/checkout@v3
      with:
        repository: 'Hyxogen/cheerp-utils'
        ref: 'feat-libasan'
    - name: Run tests
      working-directory: ./tests
      run: ./run_tests.py ${{ inputs.flags }} ${{ inputs.compiler }} ${{ inputs.runtime }}
      shell: bash
