name: "Install cheerp-compiler"
description: "Download and install the cheerp-compiler"
inputs:
  artifact:
    description: "Name of the artifact to download"
    required: true
    default: "compiler"
runs:
  using: "composite"
  steps:
    - name: Download compiler
      uses: actions/download-artifact@v3
      with:
        name: ${{ inputs.artifact }}
    - name: Untar artifacts
      run: tar -xvf cheerp-compiler.tar.zst -C /
      shell: bash
