name: "Install libasan"
description: "Install AddressSanitizer runtime libraries"
input:
  path:
    description: "Where to install the runtime library"
    required: true
    default: "/opt/cheerp"
runs:
  using: "composite"
  steps:
    - name: Checkout cheerp-compiler
      uses: actions/checkout@v3
      with:
        repository: "Hyxogen/cheerp-compiler"
        ref: 'feat-libasan'
    - name: Build runtime
      working-directory: ./compiler-rt/lib
      run: make install -j LINK_CMD=/opt/cheerp/bin/llvm-link CC=/opt/cheerp/bin/clang CXX=/opt/cheerp/bin/clang++ CHEERP_DEST="${{ inputs.path }}"
      shell: bash
