name: "Install libasan"
description: "Install AddressSanitizer runtime libraries"
inputs:
  path:
    description: "Where to install the runtime library"
    required: true
    default: "/opt/cheerp"
  config:
    description: "Build config of libasan"
    required: true
runs:
  using: "composite"
  steps:
    - name: Checkout cheerp-compiler
      uses: actions/checkout@v3
      with:
        repository: "Hyxogen/cheerp-compiler"
        ref: 'feat-libasan'
    - name: Build runtime
      working-directory: ./compiler-rt/lib
      run: make install -j config=${{ inputs.config }} CHEERP_DEST="${{ inputs.path }}"
      shell: bash
